### PR TITLE
Garble Support for Linux Payloads

### PR DESCRIPTION
**Pull request by Ne0nd0g**
Added support for [Garble](https://github.com/burrowers/garble)

Garble does help significantly obfuscate the payload, but it leaves at least these string indicators behind:

* `GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0` - From the build container
* `github.com/MythicAgents/poseidon/Payload_Type/poseidon/agent_code/_cgo_gotypes.go`
* `json:"mythic_uuid,omitempty"` - From the `DelegateMessage` structure in [definitions.go](https://github.com/MythicAgents/poseidon/blob/master/Payload_Type/poseidon/agent_code/pkg/utils/structs/definitions.go)

I tested building and executing Garbled Linux payloads, but did not test building and running macOS payloads. In _theory_ nothing was changed for the macOS payloads and everything works like it used to. :crossed_fingers: 

I did not test how the TCP comms are affected, but can go back and do so.

### CODE REVIEW

**Comment by mvdan** [comment]
The _cgo_gotypes.go case leaking the entire import path should be fixed with https://github.com/burrowers/garble/pull/559 :)

**Comment by mvdan** [comment]
> `GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0` - From the build container

This one is arguably a bug in garble as well, but I'm struggling to get rid of it. From what I can tell, I just need to tell the C toolchain (e.g. GCC) to not stamp its own name and version with `-fno-ident`. However, when called via `go build` and `import "C"`, the string is still there:

```
$ cat cgo.go
package main

// #include <stdio.h>
// #include <stdlib.h>
//
// static void myprint(char* s) {
//   printf("%s\n", s);
// }
import "C"
import "unsafe"

func main() {
	cs := C.CString("Hello from stdio")
	C.myprint(cs)
	C.free(unsafe.Pointer(cs))
}
$ go version
go version go1.18.3 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mvdan/.cache/go-build"
GOENV="/home/mvdan/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mvdan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mvdan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1709959046=/tmp/go-build -gno-record-gcc-switches"
$ CGO_CFLAGS='-g0 -O2 -fno-ident' CGO_LDFLAGS='-g0 -O2 -fno-ident' go build -trimpath -ldflags='-w -s' cgo.go
$ ./cgo 
Hello from stdio
$ strings cgo | grep 'GCC:'
GCC: (GNU) 12.1.0
```

Do either of you have any hints or pointers for me there? I have limited experience with C toolchains or cgo.

**Comment by Ne0nd0g** [comment]
I'm not very familiar with the C tool chain when used through Go, I tried to avoid it all costs. Can any of the options at https://pkg.go.dev/cmd/go be used to pass on the argument? Potentially the `-gccgoflags` or `-gcflags` arguments?

**Comment by mvdan** [comment]
gccgo flags is when using https://go.dev/doc/install/gccgo, which is using GCC to build Go code rather than Go's own compiler - it's not used by default.

gcflags is flags for the Go compiler, which are used by default, but I don't think that's where the fix would go - since it's the C compiler (GCC) rather than the Go compiler which is inserting a version.

**Pull request merged**
